apiVersion: v1
kind: Service
metadata:
  name: client-api
  namespace: local-api
spec:
  type: NodePort
  selector:
    app: client-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP